-- Tap Am database (Cloudflare D1). Money is always stored in kobo (₦1 = 100 kobo).
PRAGMA foreign_keys=ON;

-- ── people ──────────────────────────────────────────────────────────────────
-- role: USER | SPONSOR | ADMIN      tier (USER only): LAPO (free) | NEPO (paid)
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY, username TEXT NOT NULL UNIQUE COLLATE NOCASE, email TEXT UNIQUE COLLATE NOCASE,
  password_hash TEXT NOT NULL, password_salt TEXT NOT NULL, password_iter INTEGER NOT NULL DEFAULT 10000,
  role TEXT NOT NULL DEFAULT 'USER', tier TEXT NOT NULL DEFAULT 'LAPO', nepo_until TEXT, status TEXT NOT NULL DEFAULT 'ACTIVE',
  lifetime_taps INTEGER NOT NULL DEFAULT 0, games_played INTEGER NOT NULL DEFAULT 0, wins INTEGER NOT NULL DEFAULT 0, rank_level INTEGER NOT NULL DEFAULT 1,
  referral_code TEXT UNIQUE, referred_by TEXT, referral_count INTEGER NOT NULL DEFAULT 0,
  equipped_skin TEXT NOT NULL DEFAULT 'skin-boy', prefs TEXT NOT NULL DEFAULT '{}',
  date_of_birth TEXT, terms_accepted_at TEXT, terms_version TEXT, email_verified_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS sponsor_profiles (user_id TEXT PRIMARY KEY, company TEXT NOT NULL, website TEXT, logo_url TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, text TEXT NOT NULL, link TEXT, read INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);

-- ── ranks (1..100, generated by the app on first use, editable by the super admin) ──
CREATE TABLE IF NOT EXISTS ranks (level INTEGER PRIMARY KEY, name TEXT NOT NULL, min_taps INTEGER NOT NULL DEFAULT 0, min_games INTEGER NOT NULL DEFAULT 0, min_wins INTEGER NOT NULL DEFAULT 0, unlocks TEXT NOT NULL DEFAULT '', color TEXT NOT NULL DEFAULT '#00ff6e');

-- ── pools ───────────────────────────────────────────────────────────────────
-- kind: FREE | PAID | SPONSORED      audience: ALL | LAPO | NEPO      tie_rule: FIRST | SPLIT
CREATE TABLE IF NOT EXISTS pools (
  id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', starts_at TEXT NOT NULL, ends_at TEXT NOT NULL,
  entry_fee INTEGER NOT NULL DEFAULT 0, min_tier TEXT NOT NULL DEFAULT 'LAPO', boosters_allowed INTEGER NOT NULL DEFAULT 1, max_players INTEGER NOT NULL DEFAULT 1000,
  status TEXT NOT NULL DEFAULT 'SCHEDULED', created_by TEXT, hashtag TEXT UNIQUE,
  kind TEXT NOT NULL DEFAULT 'FREE', audience TEXT NOT NULL DEFAULT 'ALL', entry_fee_kobo INTEGER NOT NULL DEFAULT 0, prize_kobo INTEGER NOT NULL DEFAULT 0,
  winners_count INTEGER NOT NULL DEFAULT 1, split TEXT NOT NULL DEFAULT '[100]', tie_rule TEXT NOT NULL DEFAULT 'FIRST', house_cut_pct INTEGER NOT NULL DEFAULT 0,
  is_private INTEGER NOT NULL DEFAULT 0, join_password TEXT, sponsor_user_id TEXT, sponsor_name TEXT,
  theme_color TEXT, skin_url TEXT, game_type TEXT NOT NULL DEFAULT 'STANDARD', side_a TEXT, side_b TEXT,
  settled_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS pool_entries (
  pool_id TEXT NOT NULL, user_id TEXT NOT NULL, taps INTEGER NOT NULL DEFAULT 0, raw_taps INTEGER NOT NULL DEFAULT 0, joined_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_batch_at TEXT, settled_raw_taps INTEGER NOT NULL DEFAULT 0, side_choice TEXT, booster_item TEXT, reached_at TEXT,
  final_rank INTEGER, prize_kobo INTEGER NOT NULL DEFAULT 0, paid_kobo INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY(pool_id,user_id), FOREIGN KEY(pool_id) REFERENCES pools(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);

-- ── money ───────────────────────────────────────────────────────────────────
-- balance_kobo = wallet (money you add; spend-only)   winnings_kobo = withdrawable
CREATE TABLE IF NOT EXISTS wallets (user_id TEXT PRIMARY KEY, balance_kobo INTEGER NOT NULL DEFAULT 0, winnings_kobo INTEGER NOT NULL DEFAULT 0, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS wallet_transactions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, type TEXT NOT NULL, amount_kobo INTEGER NOT NULL, reference TEXT, status TEXT NOT NULL DEFAULT 'SUCCESS', balance TEXT NOT NULL DEFAULT 'WALLET', note TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS payments (reference TEXT PRIMARY KEY, user_id TEXT NOT NULL, purpose TEXT NOT NULL, amount_kobo INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'PENDING', provider TEXT NOT NULL DEFAULT 'paystack', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, verified_at TEXT);
CREATE TABLE IF NOT EXISTS withdrawals (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, amount_kobo INTEGER NOT NULL, bank_name TEXT, bank_code TEXT NOT NULL, account_number TEXT NOT NULL, account_name TEXT, status TEXT NOT NULL DEFAULT 'PENDING', transfer_code TEXT, admin_note TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT);

-- ── store ───────────────────────────────────────────────────────────────────
-- kind: BOOSTER | SKIN | SHAPE      audience: ALL | LAPO | NEPO
CREATE TABLE IF NOT EXISTS store_items (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', kind TEXT NOT NULL DEFAULT 'BOOSTER', price_kobo INTEGER NOT NULL DEFAULT 0, multiplier REAL NOT NULL DEFAULT 1, duration_seconds INTEGER NOT NULL DEFAULT 30, active INTEGER NOT NULL DEFAULT 1, created_by TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  audience TEXT NOT NULL DEFAULT 'ALL', min_rank INTEGER NOT NULL DEFAULT 1, config TEXT NOT NULL DEFAULT '{}', giftable INTEGER NOT NULL DEFAULT 1, sort INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS inventory (user_id TEXT NOT NULL, item_id TEXT NOT NULL, quantity INTEGER NOT NULL DEFAULT 0, acquired_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id,item_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(item_id) REFERENCES store_items(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS gifts (id TEXT PRIMARY KEY, from_user_id TEXT, to_user_id TEXT NOT NULL, item_id TEXT NOT NULL, quantity INTEGER NOT NULL, note TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

-- ── sponsors' ads ───────────────────────────────────────────────────────────
-- kind: IMAGE | YOUTUBE     placement: PRE | POST | LOBBY | ALL
CREATE TABLE IF NOT EXISTS promos (id TEXT PRIMARY KEY, title TEXT NOT NULL, owner_id TEXT, kind TEXT NOT NULL DEFAULT 'IMAGE', image_url TEXT, video_id TEXT, target_url TEXT, placement TEXT NOT NULL DEFAULT 'ALL', pool_id TEXT, active INTEGER NOT NULL DEFAULT 1, approved INTEGER NOT NULL DEFAULT 0, views INTEGER NOT NULL DEFAULT 0, clicks INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS media (key TEXT PRIMARY KEY, owner_id TEXT NOT NULL, content_type TEXT NOT NULL, size INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

-- ── voice ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS voice_sessions (user_id TEXT PRIMARY KEY, pool_id TEXT NOT NULL, session_id TEXT NOT NULL, track_name TEXT, mode TEXT NOT NULL DEFAULT 'LISTEN', updated_at TEXT NOT NULL);

-- ── misc ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS suggestions (id TEXT PRIMARY KEY, user_id TEXT, name TEXT, email TEXT, message TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'NEW', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ads (id TEXT PRIMARY KEY, slot TEXT NOT NULL UNIQUE, title TEXT NOT NULL, image_url TEXT, target_url TEXT, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY, admin_user_id TEXT, action TEXT NOT NULL, detail TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS email_codes (purpose TEXT NOT NULL, email TEXT NOT NULL COLLATE NOCASE, code_hash TEXT NOT NULL, nonce TEXT NOT NULL, payload TEXT, attempts INTEGER NOT NULL DEFAULT 0, sends INTEGER NOT NULL DEFAULT 1, last_sent_at TEXT NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(purpose,email));
CREATE TABLE IF NOT EXISTS auth_throttle (key TEXT PRIMARY KEY, count INTEGER NOT NULL, reset_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS visitors (vid TEXT PRIMARY KEY, first_seen TEXT NOT NULL, last_seen TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS merch_interest (email TEXT NOT NULL COLLATE NOCASE, item TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(email,item));

CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_pool_entries_user ON pool_entries(user_id);
CREATE INDEX IF NOT EXISTS idx_pool_entries_score ON pool_entries(pool_id,taps DESC);
CREATE INDEX IF NOT EXISTS idx_pools_dates ON pools(starts_at,ends_at);
CREATE INDEX IF NOT EXISTS idx_visitors_seen ON visitors(last_seen);
CREATE INDEX IF NOT EXISTS idx_wtx_user ON wallet_transactions(user_id,created_at);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id,read);
CREATE INDEX IF NOT EXISTS idx_promos_active ON promos(active,approved);

INSERT OR IGNORE INTO settings(key,value) VALUES
  ('landing_demo_pools','1'), ('nepo_monthly_kobo','1300000'), ('nepo_yearly_kobo','12000000'),
  ('min_withdraw_lapo_kobo','1000000'), ('min_withdraw_nepo_kobo','500000'), ('starter_boosters','3'), ('nepo_bonus_boosters','5'),
  ('referral_batch','10'), ('max_multi_pools','10'), ('voice_min_rank','56'), ('voice_top_n','5'), ('house_cut_pct','0');

INSERT OR IGNORE INTO store_items(id,name,description,kind,price_kobo,multiplier,duration_seconds,audience,min_rank,config,giftable,sort) VALUES
  ('booster-2x','Turbo 2×','Double every tap for 20 seconds.','BOOSTER',20000,2,20,'ALL',1,'{"color":"#00ff6e"}',1,1),
  ('booster-3x','Wahala 3×','Triple taps for 15 seconds.','BOOSTER',50000,3,15,'NEPO',1,'{"color":"#efc032"}',1,2),
  ('booster-5x','Odogwu 5×','Five times every tap for 10 seconds.','BOOSTER',100000,5,10,'NEPO',20,'{"color":"#e2802a"}',1,3),
  ('skin-boy','Boy tap pad','The classic boy pad.','SKIN',0,1,0,'ALL',1,'{"bg":"#1c5a33","art":"boy"}',0,10),
  ('skin-girl','Girl tap pad','The classic girl pad.','SKIN',0,1,0,'ALL',1,'{"bg":"#e2802a","art":"girl"}',0,11),
  ('skin-gold','Gold rush','Shiny gold pad for big boys.','SKIN',150000,1,0,'NEPO',1,'{"bg":"#efc032","art":"star"}',1,12),
  ('skin-kente','Kente','Woven colours, proudly ours.','SKIN',200000,1,0,'NEPO',10,'{"bg":"#d8a73a","pattern":"kente"}',1,13),
  ('skin-neon','Neon night','Glow-in-the-dark pad.','SKIN',300000,1,0,'NEPO',30,'{"bg":"#06140b","art":"bolt","glow":true}',1,14),
  ('shape-rounded','Soft corners','Rounded tap box.','SHAPE',0,1,0,'NEPO',1,'{"shape":"rounded"}',0,20),
  ('shape-circle','Circle','Round tap box.','SHAPE',50000,1,0,'NEPO',5,'{"shape":"circle"}',1,21),
  ('shape-hex','Hexagon','Six sides of pressure.','SHAPE',80000,1,0,'NEPO',15,'{"shape":"hex"}',1,22);
