-- Tap Am database (Cloudflare D1). Money is always stored in kobo (₦1 = 100 kobo).
PRAGMA foreign_keys=ON;

-- ── people ──────────────────────────────────────────────────────────────────
-- role: USER | SPONSOR | ADMIN      tier (USER only): LAPO (free) | MAPO (paid) | NEPO (premium)
-- status: ACTIVE | SUSPENDED | ARCHIVED
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY, username TEXT NOT NULL UNIQUE COLLATE NOCASE, email TEXT UNIQUE COLLATE NOCASE,
  password_hash TEXT NOT NULL, password_salt TEXT NOT NULL, password_iter INTEGER NOT NULL DEFAULT 10000,
  role TEXT NOT NULL DEFAULT 'USER', tier TEXT NOT NULL DEFAULT 'LAPO', tier_until TEXT, status TEXT NOT NULL DEFAULT 'ACTIVE',
  lifetime_taps INTEGER NOT NULL DEFAULT 0, games_played INTEGER NOT NULL DEFAULT 0, wins INTEGER NOT NULL DEFAULT 0, rank_level INTEGER NOT NULL DEFAULT 1,
  referral_code TEXT UNIQUE, referred_by TEXT, referral_count INTEGER NOT NULL DEFAULT 0,
  equipped_skin TEXT NOT NULL DEFAULT 'skin-boy', prefs TEXT NOT NULL DEFAULT '{}',
  date_of_birth TEXT, terms_accepted_at TEXT, terms_version TEXT, email_verified_at TEXT,
  gender TEXT, country TEXT, archived_at TEXT, adult_confirmed_at TEXT, emoji TEXT, emoji_meaning TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS sponsor_profiles (user_id TEXT PRIMARY KEY, company TEXT NOT NULL, website TEXT, logo_url TEXT, lead_capture INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, text TEXT NOT NULL, link TEXT, read INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);

-- ── ranks (1..100, generated by the app on first use, editable by the super admin) ──
CREATE TABLE IF NOT EXISTS ranks (level INTEGER PRIMARY KEY, name TEXT NOT NULL, min_taps INTEGER NOT NULL DEFAULT 0, min_games INTEGER NOT NULL DEFAULT 0, min_wins INTEGER NOT NULL DEFAULT 0, unlocks TEXT NOT NULL DEFAULT '', color TEXT NOT NULL DEFAULT '#00ff6e');

-- ── pools ───────────────────────────────────────────────────────────────────
-- kind: FREE | PAID | SPONSORED      audience: ALL | LAPO | NEPO      tie_rule: FIRST | SPLIT
CREATE TABLE IF NOT EXISTS pools (
  id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', starts_at TEXT NOT NULL, ends_at TEXT NOT NULL,
  entry_fee INTEGER NOT NULL DEFAULT 0, min_tier TEXT NOT NULL DEFAULT 'LAPO', boosters_allowed INTEGER NOT NULL DEFAULT 1, max_players INTEGER NOT NULL DEFAULT 1000,
  status TEXT NOT NULL DEFAULT 'SCHEDULED', created_by TEXT, hashtag TEXT UNIQUE,
  kind TEXT NOT NULL DEFAULT 'FREE', audience TEXT NOT NULL DEFAULT 'ALL', entry_fee_kobo INTEGER NOT NULL DEFAULT 0, prize_kobo INTEGER NOT NULL DEFAULT 0,
  winners_count INTEGER NOT NULL DEFAULT 1, split TEXT NOT NULL DEFAULT '[100]', tie_rule TEXT NOT NULL DEFAULT 'FIRST', house_cut_pct INTEGER NOT NULL DEFAULT 0,
  is_private INTEGER NOT NULL DEFAULT 0, join_password TEXT, sponsor_user_id TEXT, sponsor_name TEXT,
  theme_color TEXT, skin_url TEXT, game_type TEXT NOT NULL DEFAULT 'STANDARD', side_a TEXT, side_b TEXT,
  promo_id TEXT, bg_color TEXT, split_style TEXT NOT NULL DEFAULT 'TOP', vs_split INTEGER NOT NULL DEFAULT 0, pad_pattern TEXT, allow_own_pad INTEGER NOT NULL DEFAULT 0,
  settled_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS pool_entries (
  pool_id TEXT NOT NULL, user_id TEXT NOT NULL, taps INTEGER NOT NULL DEFAULT 0, raw_taps INTEGER NOT NULL DEFAULT 0, joined_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_batch_at TEXT, settled_raw_taps INTEGER NOT NULL DEFAULT 0, side_choice TEXT, booster_item TEXT, reached_at TEXT,
  final_rank INTEGER, prize_kobo INTEGER NOT NULL DEFAULT 0, paid_kobo INTEGER NOT NULL DEFAULT 0, boosters_used INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY(pool_id,user_id), FOREIGN KEY(pool_id) REFERENCES pools(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);

-- ── money ───────────────────────────────────────────────────────────────────
-- balance_kobo = wallet (money you add; spend-only)   winnings_kobo = withdrawable
CREATE TABLE IF NOT EXISTS wallets (user_id TEXT PRIMARY KEY, balance_kobo INTEGER NOT NULL DEFAULT 0, winnings_kobo INTEGER NOT NULL DEFAULT 0, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS wallet_transactions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, type TEXT NOT NULL, amount_kobo INTEGER NOT NULL, reference TEXT, status TEXT NOT NULL DEFAULT 'SUCCESS', balance TEXT NOT NULL DEFAULT 'WALLET', note TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS payments (reference TEXT PRIMARY KEY, user_id TEXT NOT NULL, purpose TEXT NOT NULL, amount_kobo INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'PENDING', provider TEXT NOT NULL DEFAULT 'paystack', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, verified_at TEXT);
CREATE TABLE IF NOT EXISTS withdrawals (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, amount_kobo INTEGER NOT NULL, bank_name TEXT, bank_code TEXT NOT NULL, account_number TEXT NOT NULL, account_name TEXT, status TEXT NOT NULL DEFAULT 'PENDING', transfer_code TEXT, admin_note TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT);

-- ── store ───────────────────────────────────────────────────────────────────
-- kind: BOOSTER | SKIN (SHAPE retired)   audience: ALL | MAPO (Mapo + Nepo) | NEPO   per_game_limit: 0 = no limit
CREATE TABLE IF NOT EXISTS store_items (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', kind TEXT NOT NULL DEFAULT 'BOOSTER', price_kobo INTEGER NOT NULL DEFAULT 0, multiplier REAL NOT NULL DEFAULT 1, duration_seconds INTEGER NOT NULL DEFAULT 30, active INTEGER NOT NULL DEFAULT 1, created_by TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  audience TEXT NOT NULL DEFAULT 'ALL', min_rank INTEGER NOT NULL DEFAULT 1, config TEXT NOT NULL DEFAULT '{}', giftable INTEGER NOT NULL DEFAULT 1, sort INTEGER NOT NULL DEFAULT 0, per_game_limit INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS inventory (user_id TEXT NOT NULL, item_id TEXT NOT NULL, quantity INTEGER NOT NULL DEFAULT 0, acquired_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id,item_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(item_id) REFERENCES store_items(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS gifts (id TEXT PRIMARY KEY, from_user_id TEXT, to_user_id TEXT NOT NULL, item_id TEXT NOT NULL, quantity INTEGER NOT NULL, note TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

-- ── sponsors' ads ───────────────────────────────────────────────────────────
-- kind: IMAGE | YOUTUBE     (placement is always ALL: before the game, in the lobby and before results)
CREATE TABLE IF NOT EXISTS promos (id TEXT PRIMARY KEY, title TEXT NOT NULL, owner_id TEXT, kind TEXT NOT NULL DEFAULT 'IMAGE', image_url TEXT, video_id TEXT, target_url TEXT, placement TEXT NOT NULL DEFAULT 'ALL', pool_id TEXT, active INTEGER NOT NULL DEFAULT 1, approved INTEGER NOT NULL DEFAULT 0, views INTEGER NOT NULL DEFAULT 0, clicks INTEGER NOT NULL DEFAULT 0, duration_seconds INTEGER NOT NULL DEFAULT 5, reject_reason TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS media (key TEXT PRIMARY KEY, owner_id TEXT NOT NULL, content_type TEXT NOT NULL, size INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

-- ── voice ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS voice_sessions (user_id TEXT PRIMARY KEY, pool_id TEXT NOT NULL, session_id TEXT NOT NULL, track_name TEXT, mode TEXT NOT NULL DEFAULT 'LISTEN', updated_at TEXT NOT NULL);

-- ── misc ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS suggestions (id TEXT PRIMARY KEY, user_id TEXT, name TEXT, email TEXT, message TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'NEW', kind TEXT NOT NULL DEFAULT 'GENERAL', data TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS slides (id TEXT PRIMARY KEY, title TEXT NOT NULL, subtitle TEXT NOT NULL DEFAULT '', image_url TEXT, link TEXT, color TEXT NOT NULL DEFAULT '#2E8BFF',
  promo_id TEXT, sponsor_id TEXT, status TEXT NOT NULL DEFAULT 'REQUESTED', sort INTEGER NOT NULL DEFAULT 0, note TEXT, views INTEGER NOT NULL DEFAULT 0, clicks INTEGER NOT NULL DEFAULT 0, cta TEXT,
  created_by TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS leads (id TEXT PRIMARY KEY, promo_id TEXT NOT NULL, sponsor_id TEXT NOT NULL, user_id TEXT NOT NULL, name TEXT NOT NULL, email TEXT, phone TEXT,
  consent_text TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(promo_id, user_id));
CREATE TABLE IF NOT EXISTS backgrounds (id TEXT PRIMARY KEY, name TEXT NOT NULL, style TEXT NOT NULL DEFAULT 'LINEAR', color_a TEXT NOT NULL, color_b TEXT NOT NULL, image_url TEXT,
  active INTEGER NOT NULL DEFAULT 1, sort INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tap_stats (period TEXT NOT NULL, user_id TEXT NOT NULL, taps INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(period, user_id));
CREATE TABLE IF NOT EXISTS badges (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, kind TEXT NOT NULL, period TEXT NOT NULL, taps INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(kind, period));
CREATE TABLE IF NOT EXISTS metrics (key TEXT NOT NULL, day TEXT NOT NULL, n INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(key, day));
CREATE TABLE IF NOT EXISTS alerts (key TEXT PRIMARY KEY, level TEXT NOT NULL, message TEXT NOT NULL, first_at TEXT NOT NULL, last_at TEXT NOT NULL, emailed_at TEXT, resolved_at TEXT);
CREATE TABLE IF NOT EXISTS ads (id TEXT PRIMARY KEY, slot TEXT NOT NULL UNIQUE, title TEXT NOT NULL, image_url TEXT, target_url TEXT, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY, admin_user_id TEXT, action TEXT NOT NULL, detail TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS email_codes (purpose TEXT NOT NULL, email TEXT NOT NULL COLLATE NOCASE, code_hash TEXT NOT NULL, nonce TEXT NOT NULL, payload TEXT, attempts INTEGER NOT NULL DEFAULT 0, sends INTEGER NOT NULL DEFAULT 1, last_sent_at TEXT NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(purpose,email));
CREATE TABLE IF NOT EXISTS auth_throttle (key TEXT PRIMARY KEY, count INTEGER NOT NULL, reset_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS visitors (vid TEXT PRIMARY KEY, first_seen TEXT NOT NULL, last_seen TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS merch (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', price_kobo INTEGER NOT NULL DEFAULT 0, image_url TEXT, color TEXT NOT NULL DEFAULT '#2E8BFF', link TEXT, status TEXT NOT NULL DEFAULT 'SOON', active INTEGER NOT NULL DEFAULT 1, sort INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
-- Special badges made by the super admin. Given badges live in `badges` with kind 'X:<id>' and period = user id.
CREATE TABLE IF NOT EXISTS special_badges (id TEXT PRIMARY KEY, name TEXT NOT NULL, meaning TEXT NOT NULL DEFAULT '', color TEXT NOT NULL DEFAULT '#9161FF', label TEXT NOT NULL DEFAULT '', active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS merch_interest (email TEXT NOT NULL COLLATE NOCASE, item TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(email,item));

CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_pool_entries_user ON pool_entries(user_id);
CREATE INDEX IF NOT EXISTS idx_pool_entries_score ON pool_entries(pool_id,taps DESC);
CREATE INDEX IF NOT EXISTS idx_pools_dates ON pools(starts_at,ends_at);
CREATE INDEX IF NOT EXISTS idx_visitors_seen ON visitors(last_seen);
CREATE INDEX IF NOT EXISTS idx_wtx_user ON wallet_transactions(user_id,created_at);
CREATE INDEX IF NOT EXISTS idx_tap_stats_user ON tap_stats(user_id, period);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id,read);
CREATE INDEX IF NOT EXISTS idx_promos_active ON promos(active,approved);
CREATE INDEX IF NOT EXISTS idx_slides_status ON slides(status, sort);
CREATE INDEX IF NOT EXISTS idx_leads_sponsor ON leads(sponsor_id, created_at);
CREATE INDEX IF NOT EXISTS idx_tap_stats_board ON tap_stats(period, taps DESC);
CREATE INDEX IF NOT EXISTS idx_badges_user ON badges(user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawals_user ON withdrawals(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_pools_creator ON pools(created_by);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_referral ON users(referral_code);

INSERT OR IGNORE INTO settings(key,value) VALUES
  ('landing_demo_pools','0'), ('nepo_monthly_kobo','5000000'), ('nepo_yearly_kobo','50000000'), ('mapo_monthly_kobo','350000'), ('mapo_yearly_kobo','3500000'),
  ('min_withdraw_lapo_kobo','1000000'), ('min_withdraw_mapo_kobo','750000'), ('min_withdraw_nepo_kobo','500000'), ('starter_boosters','3'), ('nepo_bonus_boosters','5'), ('mapo_bonus_boosters','3'),
  ('referral_batch','10'), ('max_multi_pools','10'), ('max_multi_pools_mapo','3'), ('voice_min_rank','56'), ('voice_top_n','5'), ('house_cut_pct','0'),
  ('tap_rate_lapo','15'), ('tap_rate_mapo','25'), ('tap_rate_nepo','40'), ('tap_limits_on','0'), ('tap_limit_daily','20000'), ('tap_limit_monthly','400000'),
  ('auto_payouts','0'), ('auto_payout_max_kobo','5000000'), ('auto_payout_min_age_days','7'), ('alert_email',''), ('withdrawals_per_day','1');

INSERT OR IGNORE INTO store_items(id,name,description,kind,price_kobo,multiplier,duration_seconds,audience,min_rank,config,giftable,sort,per_game_limit) VALUES
  ('booster-small','Small Chops 1.5×','Small push: 1.5× taps for 15 seconds.','BOOSTER',5000,1.5,15,'ALL',1,'{"color":"#21D4C8"}',1,0,0),
  ('booster-2x','Turbo 2×','Double every tap for 20 seconds.','BOOSTER',20000,2,20,'ALL',1,'{"color":"#00ff6e"}',1,1,0),
  ('booster-long','Long Thing 2×','Double taps for a full 45 seconds.','BOOSTER',40000,2,45,'ALL',5,'{"color":"#2E8BFF"}',1,2,0),
  ('booster-3x','Wahala 3×','Triple taps for 15 seconds.','BOOSTER',50000,3,15,'MAPO',1,'{"color":"#efc032"}',1,4,0),
  ('booster-4x','Gbas Gbos 4×','Four times every tap for 12 seconds.','BOOSTER',80000,4,12,'MAPO',10,'{"color":"#FF4FA3"}',1,5,0),
  ('booster-5x','Odogwu 5×','Five times every tap for 10 seconds.','BOOSTER',100000,5,10,'NEPO',20,'{"color":"#e2802a"}',1,6,0),
  ('booster-8x','Jaga Jaga 8×','Eight times every tap for 10 seconds. One per game.','BOOSTER',500000,8,10,'NEPO',25,'{"color":"#FF8A2A"}',1,7,1),
  ('booster-10x','Odogwu Pro 10×','Ten times every tap for 15 seconds. One per game.','BOOSTER',1500000,10,15,'NEPO',40,'{"color":"#FFD23F"}',0,8,1);
INSERT OR IGNORE INTO store_items(id,name,description,kind,price_kobo,multiplier,duration_seconds,audience,min_rank,config,giftable,sort) VALUES
  ('skin-boy','Boy tap pad','The classic boy pad: blue waves.','SKIN',0,1,0,'ALL',1,'{"bg":"#2E8BFF","pattern":"waves"}',0,10),
  ('skin-girl','Girl tap pad','The classic girl pad: pink flowers.','SKIN',0,1,0,'ALL',1,'{"bg":"#FF4FA3","pattern":"flowers"}',0,11),
  ('skin-gold','Gold rush','Shiny gold pad for big boys.','SKIN',150000,1,0,'NEPO',1,'{"bg":"#FFB800","pattern":"swirl"}',1,12),
  ('skin-kente','Kente','Woven colours, proudly ours.','SKIN',200000,1,0,'NEPO',10,'{"bg":"#d8a73a","pattern":"kente"}',1,13),
  ('skin-neon','Neon night','Glow-in-the-dark pad.','SKIN',300000,1,0,'NEPO',30,'{"bg":"#150B33","pattern":"zebra","glow":true}',1,14),
  ('skin-swirl','Swirl','Sweet-sweet swirl.','SKIN',50000,1,0,'ALL',1,'{"bg":"#9161FF","pattern":"swirl"}',1,15),
  ('skin-checker','Checker','Draughts board energy.','SKIN',50000,1,0,'ALL',1,'{"bg":"#FF8A2A","pattern":"checker"}',1,16),
  ('skin-stripes','Stripes','Clean diagonal stripes.','SKIN',50000,1,0,'ALL',1,'{"bg":"#21D4C8","pattern":"stripes"}',1,17),
  ('skin-ripple','Ripple','Water wey dey move.','SKIN',100000,1,0,'MAPO',1,'{"bg":"#2E8BFF","pattern":"ripple"}',1,18),
  ('skin-cow','Cow print','Moo moo, tap tap.','SKIN',100000,1,0,'MAPO',1,'{"bg":"#F4F0FF","pattern":"cow"}',1,19),
  ('skin-daisy','Daisy','Flowers for the soft tappers.','SKIN',100000,1,0,'MAPO',1,'{"bg":"#9161FF","pattern":"flowers"}',1,20),
  ('skin-leopard','Leopard','Fast like cat.','SKIN',150000,1,0,'MAPO',10,'{"bg":"#FFD23F","pattern":"leopard"}',1,21),
  ('skin-zebra','Zebra','Black and white, no shaking.','SKIN',200000,1,0,'NEPO',10,'{"bg":"#F4F0FF","pattern":"zebra"}',1,22);

INSERT OR IGNORE INTO backgrounds(id,name,style,color_a,color_b,sort) VALUES
  ('bg-sunset','Lagos sunset','LINEAR','#FF8A2A','#9B1FD8',1), ('bg-ocean','Atlantic','LINEAR','#0BC5EA','#2A2BB8',2),
  ('bg-forest','Naija green','RADIAL','#00C957','#0A3B2A',3), ('bg-night','Owambe night','LINEAR','#1B0B4D','#FF4FA3',4),
  ('bg-gold','Gold rush','RADIAL','#FFD23F','#B35A00',5), ('bg-candy','Bubblegum','LINEAR','#FF7AC6','#7B45FF',6);
