name = "tap-am"
main = "worker.js"
compatibility_date = "2026-10-07"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "tap-am-demo"
database_id = "be374827-0931-462b-8cfd-50b897e11594"
